# Generated by Django 4.2.1 on 2023-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="date_from",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="date_to",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[("past", "Past"), ("now", "Now"), ("planned", "Planned")],
                default="now",
                max_length=10,
            ),
        ),
    ]
