# Generated by Django 4.2.1 on 2023-05-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_delivery_date_from_delivery_date_to_delivery_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="date_from",
            new_name="date_end",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="address",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="date_to",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="name",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[("past", "Past"), ("now", "Now")], default="now", max_length=10
            ),
        ),
    ]
