# Generated by Django 4.2.1 on 2023-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                ("date", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("avia", "Avia"),
                            ("train", "Train"),
                            ("track", "Track"),
                        ],
                        default="track",
                        max_length=10,
                    ),
                ),
                ("products", models.ManyToManyField(to="orders.product")),
            ],
        ),
    ]
