# Generated by Django 4.2.1 on 2023-05-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="address_type",
            field=models.CharField(
                choices=[("kz", "KZ"), ("ru", "RU"), ("uz", "UZ"), ("kg", "KG")],
                default="kg",
                max_length=20,
                verbose_name="Address Type",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
