# Generated by Django 4.2.1 on 2023-05-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_address_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="number",
        ),
    ]
