# Generated by Django 4.2.1 on 2023-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_status",
            field=models.CharField(
                choices=[("past", "Past"), ("now", "Now")], default="now", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
