# Generated by Django 4.2.1 on 2023-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_order_products_order_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(blank=True, to="orders.product"),
        ),
    ]
